Upgrade nodejs required
Passage de nodejs V10 à V12
pour pouvoir `fields.flat` nécessaire dans la commande d'aide

Erreur sous nodejs V10
```
(node:21750) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/mathi/tempTest/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/mathi/tempTest/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/mathi/tempTest/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at bot.commands.each.command (/home/mathi/tempTest/commands/help.js:32:19)
    at Map.forEach (<anonymous>)
    at Map.each (/home/mathi/tempTest/node_modules/@discordjs/collection/dist/index.js:282:14)
    at Object.exports.run (/home/mathi/tempTest/commands/help.js:16:18)
    at Object.exports.run (/home/mathi/tempTest/events/message.js:24:25)
    at Client.bot.on.args (/home/mathi/tempTest/bot.js:88:45)
    at Client.emit (events.js:198:13)
```